### PR TITLE
Update to DLL with world corruption fix

### PR DESCRIPTION
**Pull request by Moneylover3246**

### CODE REVIEW

**Review by hakusaro — CHANGES_REQUESTED** [review]
Version number did not change?

**Comment by hakusaro** [comment]
Also, you probably need a warning if you're still turning off STR handling in TShock with your plugin so that people have proper expectations

**Comment by Moneylover3246** [comment]
The updated commit will have a new release for TShock-handled SendTileRect

**Comment by hakusaro** [comment]
> The updated commit will have a new release for TShock-handled SendTileRect

Is that the one currently up or coming later?

**Comment by hakusaro** [comment]
Screen Shot 2021-06-03 at 00 20 08

Hmm, you seem to be doing this the hard way. I really don't suggest that you reimplement most of bouncer in your plugin. If you need to copy it directly (you shouldn't), can you change all of the log messages? Unfortunately, you're using debug messages which are "imitating TShock's" and that could cause confusion later (for example, if we fix a bug in Bouncer but you don't propagate that, and we get bug reports with these log messages).

If you need TShock changed to better be able to support what you're doing, you can let us know and we can affect changes. If i were you, I would hook the things that TShock hooks at a higher priority, and then just handle events that aren't relevant. If you're having problems because the handler is too late, we can always change that or change TShock's priority.

**To merge, though, fundamentally, we can't accept log messages like this long term.**

P.S. You're compiling your plugin in **debug** mode, just so you're aware.

**Comment by hakusaro** [comment]
@Moneylover3246 soz, what're the blockers on this one again?

**Review by hakusaro — APPROVED** [review]

**Pull request merged**
