### PR TITLE
Submission for ListPluginsPlugin

### PR DESCRIPTION
**Pull request by Arthri**
Provides `/lplg`, for listing currently loaded plugins

### CODE REVIEW

**Review by hakusaro — CHANGES_REQUESTED** [review]
Hi! Thank you for your submission! Can you remove the alternate download link you have? We only permit catbox direct download links on the plugin repo page, since anyone can simply change the other release file after it's been reviewed, which would be bad.

**Comment by Arthri** [comment]
> Hi! Thank you for your submission! Can you remove the alternate download link you have? We only permit catbox direct download links on the plugin repo page, since anyone can simply change the other release file after it's been reviewed, which would be bad.

:+1: done. I understand

**Review by hakusaro — APPROVED** [review]
Screen Shot 2021-08-02 at 22 35 17

Why not just `/plugins`? Should this just be [sherlocked](https://appleinsider.com/articles/19/06/06/developers-talk-about-being-sherlocked-as-apple-uses-them-for-market-research) by tsapi?

**Comment by hakusaro** [comment]
Screen Shot 2021-08-02 at 22 39 41

The bundled GPL license is seriously how much bigger than the assembly?

**Comment by Arthri** [comment]
> Screen Shot 2021-08-02 at 22 35 17
> 
> Why not just `/plugins`? Should this just be [sherlocked](https://appleinsider.com/articles/19/06/06/developers-talk-about-being-sherlocked-as-apple-uses-them-for-market-research) by tsapi?

both sound good :+1:, I don't mind it being implemented into TSAPI. Though since the command API is in TShock I'm not sure how you'll do it

**Comment by Arthri** [comment]
> Screen Shot 2021-08-02 at 22 39 41
> 
> The bundled GPL license is seriously how much bigger than the assembly?

I apologize for the file size. The plugin was written before the discussion on licenses 😅. Though, I don't mind relicensing it under MIT if you want

**Comment by hakusaro** [comment]
> I apologize for the file size.

oh I don’t mind, but think of all of the 5G

**Comment by hakusaro** [comment]
> Though since the command API is in TShock I'm not sure how you'll do it

Probably a startup or something to solve this problem. We’ll call it “plug” for short. #pluggedin

**Pull request merged**
