### PR TITLE
added tshock mobile server manager

### PR DESCRIPTION
**Pull request by KohlsAdrian**

### CODE REVIEW

**Comment by hakusaro** [comment]
Would you be opposed to publishing App Store versions of these?

**Comment by KohlsAdrian** [comment]
Maybe play store of Android if it is ok to publish. If not, I won't publish.
But AppStore I have no license, because: $$$

Only available for manual download or building on it own.

**Comment by KohlsAdrian** [comment]
No, I would not oppose. I just won't publish for my self because I don't have AppStore license, only Google Play, because Apple is high $$$

**Comment by KohlsAdrian** [comment]
If it is ok, I can publish the Android version of the app as I have my Google Play account since 2014

**Comment by hakusaro** [comment]
Of course. It's yours. You can do whatever!

On February 18, 2021, GitHub <notifications@github.com> wrote:
> If it is ok, I can publish the Android version of the app as I have my

> Google Play account since 2014
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Pryaxis/Plugins/pull/31#issuecomment-781521888>, or

unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAECBJZDP2B4XKCGFJJHR7DS7VHBXANCNFSM4XYZ4FRQ>.

**Review by hakusaro — APPROVED** [review]

**Comment by KohlsAdrian** [comment]
Updated Wrapper and Client repos with google play link for client manager

**Pull request merged**
