### PR TITLE
Add WorldMapper to README.md

### PR DESCRIPTION
**Pull request by drunderscore**
Feels a bit mean to add it to the top of the list, but that's what previous commits have done.

Perhaps alphabetically order plugins in the future?

Tested on Mono running under Linux, _not_ tested on Windows -- I say this out of fear of possible `System.Drawing` weirdness.

### CODE REVIEW

**Review by hakusaro — CHANGES_REQUESTED** [review]
1. Please resolve conflicts
2. Please upload to catbox
3. If you're self conscious, please move to lower on list, not top of list

**Review by hakusaro — CHANGES_REQUESTED** [review]
You cannot provide "alternate download" links. Please remove alternate download links.

**Comment by drunderscore** [comment]
Alternative download removed

**Comment by hakusaro** [comment]
Screen Shot 2021-07-29 at 22 35 01


On Linux. You did this on Linux.

**Review by hakusaro — APPROVED** [review]
lgtm_1


Thank you for the plugin!

**Review by hakusaro — APPROVED** [review]

**Pull request merged**
