### PR TITLE
Update Smart Regions

### PR DESCRIPTION
**Pull request by ZakFahey**
It was updated with this change: https://github.com/ZakFahey/SmartRegions/commit/8bf51be867f0d24b18b153fc124dbcb777aa44b6

### CODE REVIEW

**Comment by ZakFahey** [comment]
Hmm actually this would break regions with commands that did something like `/bc [PLAYERNAME] is so cool!`, things where you're displaying text rather than using the player name to do a lookup.

**Comment by bartico6** [comment]
[commandplayer] and [player] maybe?

**Comment by ZakFahey** [comment]
Yes I would consider the problem I mentioned a TODO. The issue is kind of low priority for me. You can merge it.

**Comment by ZakFahey** [comment]
Also for backwards compatibility reasons [PLAYERNAME] would stay, of course. If anything there would be a new keyword, not a replacement of the old one.

**Review by hakusaro — CHANGES_REQUESTED** [review]
Can you update the `AssemblyVersion` to 1.3.1?

**Comment by ZakFahey** [comment]
Sure, done.

**Comment by hakusaro** [comment]
@ZakFahey thank you! Unfortunately, due to an administrative issue, we are delaying plugin processing by +2 days so that I can focus on rectifying that. Thank you for your update!

**Comment by hakusaro** [comment]
lgtm_8

**Review by hakusaro — APPROVED** [review]
lgtm_1

**Pull request merged**
